all:	pdf supp

pdf:	ccTutorial.tex
	cp ../inst/vignettes/ccTutorial.pdf ../inst/doc
	#cp -f ../vignettes/ccTutorial.Rnw .

supp:	ccTutorialSupplement.tex
	cp ../inst/vignettes/ccTutorialSupplement.pdf ../inst/doc
	#cp -f ../vignettes/ccTutorialSupplement.Rnw .
