all:	pdf supp

pdf:	ccTutorial.tex
	cp ../vignettes/ccTutorial.pdf .
	cp -f ../vignettes/ccTutorial.Rnw .

supp:	ccTutorialSupplement.tex
	cp ../vignettes/ccTutorialSupplement.pdf .
	cp -f ../vignettes/ccTutorialSupplement.Rnw .
